name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.19.0
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.6.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: 
  flutter_bloc: 
  form_bloc:
    git:
      url: git://github.com/cyan92128505/form_bloc.git
      path: packages/form_bloc
  rxdart: 
  flutter_keyboard_visibility: 
  collection: 
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0
